### ISSUE TITLE
Dúvidas em glossário

### ISSUE THREAD

**Issue by beatrizmilz** [clente/pt-bR#3]
- caller. exemplo: ' should be specified by the caller' em utils

**Comment by beatrizmilz** [comment]
unlisted - foi traduzido como deslistado. faria sentido usar 'não listado'?

**Comment by beatrizmilz** [comment]
como traduzir 'profile'? perfil?

**Comment by beatrizmilz** [comment]
https://translate.rx.studio/browse/r-project/glossary/pt_BR/

**Comment by beatrizmilz** [comment]
non-interactively: de forma não interativa? não interativamente?

**Comment by clente** [comment]
- _Caller_: eu traduziria como "chamador(a)". Nesse caso específico, acho que podemos evitar o gênero: "deve ser especificado".
- _Unlisted_: eu pessoalmente prefiro "não listado".
- _Profile_: se for substantivo é "perfil", mas, se for verbo, é "perfilar" ([fonte](https://www.linguee.com/english-portuguese/search?query=profile)).
- _Non-interactively_: eu pessoalmente prefiro "de forma não interativa".
